version: "1.0"

services:
  bot:
    build:
      context: ./bot
    env_file:
      - .env
    restart: always
    volumes:
      - ./bot:/bot

  db:
    image: postgres:15
    container_name: telegram_bot_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
