version: "3.8"

services:
  db:
    image: postgres:15
    container_name: tg_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    image: tg_fastapi:latest
    container_name: tg_fastapi
    build:
      context: ./backend
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"

  bot:
    image: tg_bot:latest
    container_name: tg_bot
    build:
      context: ./bot
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - fastapi
    volumes:
      - ./bot:/bot

volumes:
  postgres_data:
